### ISSUE TITLE
The test results

### ISSUE THREAD

**Issue by cyr999** [haidongz-usc/Curriculum-DeepSDF#1]
Hello, may I ask why there is a big gap between the test results of the code used and the results of the paper? What is the problem

**Comment by haidongz-usc** [comment]
Hi, thanks for your interest in our work! May I please ask how big the gap at your end is? Can you please provide more details about the problem? We have already posted our generated meshes with the link in the Readme file, so there might be some possibilities:
- If you cannot achieve the CD, EMD, and other numbers with the generated meshes we provided, I think there is something wrong with your evaluation code, or the groundtruth meshes you generated don't match with the files we use (as the DeepSDF). The CD for current meshes should be near 0.000473 for the lamp category.
- If you directly evaluate the generated mesh with the groundtruth and get similar results as the paper, but you fail to reproduce the results with the pretrained models, there might be some problem with the inference code, or the preprocessing code use might not match with ours. 

Hope this helps you. Thanks!

**Comment by cyr999** [comment]
We use "python eval2.py -e examples/lamps  -c 2000 -d data -s examples/splits/sv2_lamps_test.json" in your code for evaluation, and the evaluation result is 0.000689, not 0.000473.
In addition, is the evaluation metric only CD distance?
Thank you very much for your reply.

**Comment by haidongz-usc** [comment]
Thanks for your response! 

For the numbers you mentioned, we rerun the evaluation code provided in this GitHub repo, and still gets the similar results as we reported in paper. Here is the log file to the result. [eval_results.txt](https://github.com/haidongz-usc/Curriculum-DeepSDF/files/6735303/eval_results.txt). The average CD of this file is 0.0004734 and the median CD is 0.00010627, which is similar to the numbers we report in the paper (0.000105). The small difference here is due to the points that sampled from the mesh for evaluation. The difference between your numbers and ours might be due to the different preprocessing settings.

For the evaluation metric, we follow the deepSDF since they only provide the CD function. The EMD is pretty slow during evaluation, and that's another reason we didn't include it in the file. If you are interested, here is the EMD and mesh accuracy functions we use during our experiment.

```
import numpy as np
import trimesh
from scipy.spatial.distance import cdist
from scipy.optimize import linear_sum_assignment

def EMD(Y1, Y2): 
    # input - two N x 3 numpy array
    d = cdist(Y1, Y2)
    assignment = linear_sum_assignment(d)
    return d[assignment].sum() / Y1.shape[0]

def mesh_acc(mesh, sampled_points):
    # input - mesh : trimesh.base.Trimesh of the input mesh
    #         sampled_points : sampled points with N x 3 numpy array format
    dist = trimesh.proximity.signed_distance(mesh, sampled_points)
    dist = np.abs(dist)
    dist.sort()
    return dc[dc.shape[0] * 9 // 10]
```

Thanks!

**Comment by cyr999** [comment]
Thank you very much for your reply:

The model you gave on GitHub was used for reconstruction and evaluation, and the final result was 0.755, which was higher than the result of my own retraining and evaluation. However, except for the large difference in the category of  lamps, the other four categories did not differ much from the experimental results in the paper. I guess the number of lamps' sample  was too small, so I do not know whether this is the reason.

Looking forward to your reply!

**Comment by haidongz-usc** [comment]
Thank you for the confirmation! Yes that might be the case. I agree the problem for the lamp might be that the points for one or two of the samples are greatly different with the samples we use, which cause this problem.
